---
# tasks file for roles/launch_proxy
- name: Run ReverseProxy
  docker_container:
    name: httpd
    image: massichalal/tp-devops-httpd
    networks:
      - name: app-network
    ports:
      - "80:80"
  vars:
    ansible_python_interpreter: /usr/bin/python3
