# tasks file for roles/database
- name: Run database
  docker_container:
    name: database
    image: massichalal/tp-devops-database
    networks:
      - name: app-network
    ports:
      - "5432:5432"
  vars:
    ansible_python_interpreter: /usr/bin/python3